---
kind: pipeline
name: janus-gateway

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: docker.internal.walbeck.it/walbeck-it/janus-gateway
      registry: docker.internal.walbeck.it
      tags:
        - latest
