---
kind: pipeline
name: janus-gateway_build

steps:
  - name: determine tags
    image: bash
    environment:
      APP: "JANUS"
      DIR: ""
      CUSTOM_TAGS: "latest,"
    commands:
      - apk add --no-cache grep
      - VER=$(grep "ENV $${APP}_VERSION" $${DIR:-}Dockerfile)
      - VER=$${VER##* }
      - VER=$${VER#v}
      - TAGS="$${CUSTOM_TAGS:-}"
      - TAGS="$TAGS$VER,"
      - VER=$${VER%.*}
      - TAGS="$TAGS$VER"
      - echo -n $TAGS > .tags
      - echo $TAGS

  - name: build and publish
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: docker.internal.walbeck.it/walbeck-it/janus-gateway
      registry: docker.internal.walbeck.it

trigger:
  branch:
    - master
  event:
    - push

---
kind: pipeline
name: janus-gateway_test

steps:
  - name: build test
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: docker.internal.walbeck.it/walbeck-it/janus-gateway
      registry: docker.internal.walbeck.it
      dry_run: true

trigger:
  event:
    - pull_request
